In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("insurance.csv")
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.tail()

age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [8]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [9]:
df.duplicated().sum()

np.int64(1)

In [10]:
df.isnull()

age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [11]:
df.isnull().sum()


age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [12]:
df.drop_duplicates(inplace=True)  ###inplace == true
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [13]:
df.duplicated().sum() 

np.int64(0)

In [14]:
df.dropna() 

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [15]:
df['sex'] 

0       female
1         male
2         male
3         male
4         male
         ...  
1333      male
1334    female
1335    female
1336    female
1337    female
Name: sex, Length: 1337, dtype: object

In [16]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [17]:
df['sex'].value_counts() 

sex
male      675
female    662
Name: count, dtype: int64

In [18]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [19]:
df.drop(['region'],axis=1,inplace=True)

In [20]:
df

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1337 rows x 6 columns]

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [23]:
df['smoker'] 

0       yes
1        no
2        no
3        no
4        no
       ... 
1333     no
1334     no
1335     no
1336     no
1337    yes
Name: smoker, Length: 1337, dtype: object

In [24]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [25]:
df['smoker'].value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [26]:
sex_dict = {
    'female': 1,
    'male': 2
}

In [27]:
sex_dict

{'female': 1, 'male': 2}

In [28]:
df['sex']=df['sex'].map(sex_dict)

In [29]:
df

age  sex     bmi  children smoker      charges
0      19    1  27.900         0    yes  16884.92400
1      18    2  33.770         1     no   1725.55230
2      28    2  33.000         3     no   4449.46200
3      33    2  22.705         0     no  21984.47061
4      32    2  28.880         0     no   3866.85520
...   ...  ...     ...       ...    ...          ...
1333   50    2  30.970         3     no  10600.54830
1334   18    1  31.920         0     no   2205.98080
1335   18    1  36.850         0     no   1629.83350
1336   21    1  25.800         0     no   2007.94500
1337   61    1  29.070         0    yes  29141.36030

[1337 rows x 6 columns]

In [30]:
smoker_dict = {
    'no': 1,
    'yes': 2
}

In [31]:
smoker_dict

{'no': 1, 'yes': 2}

In [32]:
df['smoker']=df['smoker'].map(smoker_dict)

In [33]:
df

age  sex     bmi  children  smoker      charges
0      19    1  27.900         0       2  16884.92400
1      18    2  33.770         1       1   1725.55230
2      28    2  33.000         3       1   4449.46200
3      33    2  22.705         0       1  21984.47061
4      32    2  28.880         0       1   3866.85520
...   ...  ...     ...       ...     ...          ...
1333   50    2  30.970         3       1  10600.54830
1334   18    1  31.920         0       1   2205.98080
1335   18    1  36.850         0       1   1629.83350
1336   21    1  25.800         0       1   2007.94500
1337   61    1  29.070         0       2  29141.36030

[1337 rows x 6 columns]

In [34]:
df.dropna(inplace=True)

In [35]:
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
charges     float64
dtype: object

In [36]:
df.to_csv('clean_insurance.csv')

In [37]:
df.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
charges     float64
dtype: object

In [38]:
x = df.drop('charges', axis = 1)
y = df[['charges']]

In [39]:
x

age  sex     bmi  children  smoker
0      19    1  27.900         0       2
1      18    2  33.770         1       1
2      28    2  33.000         3       1
3      33    2  22.705         0       1
4      32    2  28.880         0       1
...   ...  ...     ...       ...     ...
1333   50    2  30.970         3       1
1334   18    1  31.920         0       1
1335   18    1  36.850         0       1
1336   21    1  25.800         0       1
1337   61    1  29.070         0       2

[1337 rows x 5 columns]

In [40]:
y

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1337 rows x 1 columns]

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42, test_size = 0.2)

In [42]:
x_train

age  sex     bmi  children  smoker
1114   23    2  24.510         0       1
968    21    2  25.745         2       1
599    52    1  37.525         2       1
170    63    2  41.470         0       1
275    47    1  26.600         2       1
...   ...  ...     ...       ...     ...
1096   51    1  34.960         2       2
1131   27    2  45.900         2       1
1295   20    2  22.000         1       1
861    38    1  28.000         3       1
1127   35    1  35.860         2       1

[1069 rows x 5 columns]

In [43]:
y

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1337 rows x 1 columns]

In [44]:
x_test

age  sex     bmi  children  smoker
900    49    2  22.515         0       1
1064   29    1  25.600         4       1
1256   51    1  36.385         3       1
298    31    2  34.390         3       2
237    31    2  38.390         2       1
...   ...  ...     ...       ...     ...
534    64    2  40.480         0       1
542    63    1  36.300         0       1
760    22    1  34.580         2       1
1284   61    2  36.300         1       2
1285   47    1  24.320         0       1

[268 rows x 5 columns]

In [45]:
y_test

charges
900    8688.85885
1064   5708.86700
1256  11436.73815
298   38746.35510
237    4463.20510
...           ...
534   13831.11520
542   13887.20400
760    3925.75820
1284  47403.88000
1285   8534.67180

[268 rows x 1 columns]

In [46]:
x_test.shape,y_test.shape,x_train.shape,y_train.shape

((268, 5), (268, 1), (1069, 5), (1069, 1))

In [47]:
from sklearn.svm import SVR
sv= SVR()
sv.fit(x_train,y_train)
print(sv.score(x_train,y_train))
print(sv.score(x_test,y_test))

c:\Users\STM\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


-0.10149330293783043
-0.13444584199005627


In [48]:
from sklearn.datasets import load_iris
x , y = load_iris(return_X_y=True)

In [49]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [50]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
from sklearn .svm import SVC
sv = SVC()
sv.fit(x, y)

SVC()

In [52]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x, y)
knn.score(x, y)

0.9666666666666667

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [55]:
lr.score(x_test,y_test)

0.8046218811772661

In [56]:
pred=lr.predict(x_test)

In [57]:
pred

array([[ 7780.09204548],
       [ 5977.83338997],
       [14215.82300956],
       [31590.59473466],
       [ 9223.64922442],
       [13438.43822409],
       [29841.65667782],
       [ 1685.03795715],
       [10919.46514725],
       [11281.04050309],
       [10418.78669104],
       [33059.36084168],
       [30531.50988264],
       [17420.0023959 ],
       [10214.90616935],
       [ 9749.75223135],
       [ 4298.47335596],
       [32007.67725019],
       [ 3488.96062241],
       [ 5583.27330599],
       [ 3845.53703027],
       [29815.02239719],
       [15103.39914515],
       [30646.34708594],
       [30908.30211535],
       [ 5363.08477297],
       [35705.172843  ],
       [36714.56751572],
       [10928.83748576],
       [13689.22034633],
       [ 5994.25520485],
       [13015.10761713],
       [  842.10884744],
       [12332.40611586],
       [39769.78804625],
       [12472.16793437],
       [ 4941.6340669 ],
       [ 3962.34504306],
       [31334.30270026],
       [ 9347.27340131],


In [58]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [59]:
dt.score(x_test, y_test)

0.7856679211052647

In [60]:
import joblib
joblib.dump(dt, 'model.joblib')

['model.joblib']

In [61]:
model = joblib.load('model.joblib')

In [62]:
model.predict(x_test)

array([ 9361.3268 ,  4877.98105, 10848.1343 , 44585.45587,  4673.3922 ,
       10370.91255, 37484.4493 ,  2007.945  , 19144.57652, 10702.6424 ,
       13616.3586 , 23065.4207 , 51194.55914, 12982.8747 ,  5836.5204 ,
       32108.66282,  2362.22905, 39774.2763 , 23241.47453,  4149.736  ,
        1748.774  , 20296.86345, 10370.91255, 20296.86345, 37079.372  ,
        7418.522  , 43753.33705, 45710.20785,  9910.35985,  9563.029  ,
        3761.292  ,  9386.1613 ,  1837.237  , 12913.9924 , 48549.17835,
        9283.562  ,  4915.05985,  4906.40965, 22412.6485 ,  8823.279  ,
        2026.9741 , 18767.7377 , 41034.2214 ,  9290.1395 ,  9500.57305,
        3353.284  ,  1634.5734 ,  7727.2532 ,  4527.18295,  6986.697  ,
        4922.9159 ,  5438.7491 , 21880.82   ,  1880.487  ,  7160.3303 ,
        8116.26885,  9617.66245,  3208.787  , 51194.55914,  6600.361  ,
       11299.343  ,  5246.047  , 11488.31695,  1708.0014 , 11396.9002 ,
       12094.478  ,  6112.35295, 21774.32215, 16884.924  , 12347

In [63]:
y_test

charges
900    8688.85885
1064   5708.86700
1256  11436.73815
298   38746.35510
237    4463.20510
...           ...
534   13831.11520
542   13887.20400
760    3925.75820
1284  47403.88000
1285   8534.67180

[268 rows x 1 columns]